apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-bvom
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/nbe-e2e-esrb-tenant/integ-app-nojy/hacbs-test-project-bvom@sha256:dc3cf9a72a423100ebac5b47fc67d6a675990f28aaa4ed8ea9db1e04433f5192
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
